### ISSUE TITLE
请问直接copy例子为何运行不起

### ISSUE THREAD

**Issue by lxmbetterman** [vhtml/webpack-MultiPage-static#6]
直接copy例子为何运行不起 @vhtml #
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\NODE\\node.exe',
1 verbose cli   'C:\\NODE\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\NODE\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at C:\NODE\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at C:\NODE\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (C:\NODE\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (C:\NODE\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (C:\NODE\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at C:\NODE\node_modules\npm\node_modules\read-package-json\read-json.js:232:12
4 verbose stack     at C:\NODE\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd F:\PROtest\webpackmultiPage
6 error Windows_NT 6.1.7601
7 error argv "C:\\NODE\\node.exe" "C:\\NODE\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
8 error node v4.4.3
9 error npm  v2.15.1
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by lxmbetterman** [comment]
发现原因了：
package.json文件里 应该指定
"scripts": {
    "start": "webpack-dev-server --inline"
  },
表示启动打包指令  inline表示实时打包  修改一个代码更新一下
